### ISSUE TITLE
Error when running bigpicture

### ISSUE THREAD

**Issue by sdil** [ismailbayram/bigpicture#4]
I'm running `bigpicture server` on my private project and I got the following error:

```
> bigpicture server
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x18 pc=0x104a872c4]

goroutine 1 [running]:
github.com/ismailbayram/bigpicture/internal/graph.(*Tree).CalculateInstability(0x140004621e0)
	/Users/fyaacob/go/pkg/mod/github.com/ismailbayram/bigpicture@v0.0.0-20231225173050-bad25457eb91/internal/graph/graph.go:57 +0x1d4
main.main()
	/Users/fyaacob/go/pkg/mod/github.com/ismailbayram/bigpicture@v0.0.0-20231225173050-bad25457eb91/main.go:57 +0x310
```

I'm not sure what went wrong here and no idea how to debug from this stacktrace. Anyone can help me?

I'm using v1.2.2

**Comment by ismailbayram** [comment]
Hi, thank you for your question.
I think there is a bug in the bigpicture because of Calculation of Instability.
Could you please remove instability configs from your .bigpicture.json file?

**Comment by sdil** [comment]
@ismailbayram I did not set instability validation in the config. this is my `.bigpicture.json` file:

```json
{
  "lang": "go",
  "ignore": [
    "doc",
    ".gen",
    "migrations",
    "cmd"
  ],
  "validators": [
    {
      "type": "no_import",
      "args": {
        "from": "*",
        "to": "/models",
        "ignore": [
          "/internal"
        ]
      }
    },
    {
      "type": "no_import",
      "args": {
        "from": "*",
        "to": "/internal/apps/*",
        "ignore": [
          "/pkg",
          "/cmd",
          "/internal/apps"
        ]
      }
    },
    {
      "type": "no_import",
      "args": {
        "from": "*",
        "to": "/pkg/middleware/*",
        "ignore": [
          "/pkg",
          "/pkg/apiserver"
        ]
      }
    }
  ]
}
```

**Comment by ismailbayram** [comment]
Could you share your project structure, please?

**Comment by sdil** [comment]
@ismailbayram this is the folder structure looks like

```
fyaacob@M1622 ~/p/p/money-manager (main)> tree .
.
├── Makefile
├── cmd
│   └── web
│       └── main.go
├── doc
│   └── openapi.json
├── docker-compose.yaml
├── go.mod
├── go.sum
├── internal
│   ├── apps
│   │   ├── services.go
│   │   ├── transaction
│   │   └── user
│   │       ├── actor.go
│   │       └── user.go
│   └── managers
│       ├── managers.go
│       └── user.go
├── migrations
│   └── 20241119142056_create_user_tabl.sql
└── pkg
    ├── adminserver
    ├── apiserver
    │   ├── router.go
    │   └── routes
    │       └── user.go
    ├── auth
    │   └── verify.go
    ├── customcontext
    │   └── user.go
    ├── infrastructure
    │   ├── actor
    │   │   └── goakt.go
    │   ├── db
    │   │   └── postgres.go
    │   └── prometheus
    └── middleware
        ├── requestlog.go
        └── setusercontext.go

21 directories, 20 files
```

I'm using [jet](https://github.com/go-jet/jet/) in `.gen/` directory.

The project compiles fine and the web server is running successfully.

I'm pretty sure the issue is caused by package import in one of the go file but I could'nt figure out which one.

**Comment by ismailbayram** [comment]
I've published a new version 1.2.3.
Could you try it again, please?

**Comment by sdil** [comment]
@ismailbayram thanks for the new update. This is what I get now:

```
> bigpicture server
panic: 47:38: expected statement, found ')'

goroutine 1 [running]:
github.com/ismailbayram/bigpicture/internal/browser.(*GoBrowser).parseFile(0x140003fde90, {0x140004149a0, 0x1e}, 0x1400045de80)
	/Users/fyaacob/go/pkg/mod/github.com/ismailbayram/bigpicture@v0.0.0-20241206080752-15f269f8a114/internal/browser/go.go:71 +0x51c
github.com/ismailbayram/bigpicture/internal/browser.(*GoBrowser).browse(0x140003fde90, {0x140002e2990, 0x16}, 0x1400045de80)
	/Users/fyaacob/go/pkg/mod/github.com/ismailbayram/bigpicture@v0.0.0-20241206080752-15f269f8a114/internal/browser/go.go:54 +0x1bc
github.com/ismailbayram/bigpicture/internal/browser.(*GoBrowser).browse(0x140003fde90, {0x14000474080, 0xf}, 0x1400045d980)
	/Users/fyaacob/go/pkg/mod/github.com/ismailbayram/bigpicture@v0.0.0-20241206080752-15f269f8a114/internal/browser/go.go:51 +0x2b0
github.com/ismailbayram/bigpicture/internal/browser.(*GoBrowser).browse(0x140003fde90, {0x1400041bec8, 0x5}, 0x1400045d400)
	/Users/fyaacob/go/pkg/mod/github.com/ismailbayram/bigpicture@v0.0.0-20241206080752-15f269f8a114/internal/browser/go.go:51 +0x2b0
github.com/ismailbayram/bigpicture/internal/browser.(*GoBrowser).browse(0x140003fde90, {0x102502b80, 0x1}, 0x140003eba00)
	/Users/fyaacob/go/pkg/mod/github.com/ismailbayram/bigpicture@v0.0.0-20241206080752-15f269f8a114/internal/browser/go.go:51 +0x2b0
github.com/ismailbayram/bigpicture/internal/browser.(*GoBrowser).Browse(0x140003fde90, {0x102502b80, 0x1})
	/Users/fyaacob/go/pkg/mod/github.com/ismailbayram/bigpicture@v0.0.0-20241206080752-15f269f8a114/internal/browser/go.go:22 +0x68
main.main()
	/Users/fyaacob/go/pkg/mod/github.com/ismailbayram/bigpicture@v0.0.0-20241206080752-15f269f8a114/main.go:55 +0x300
```

**Comment by sdil** [comment]
@ismailbayram i can find the error now when i run `go fmt ./...` now!

```
> go fmt ./...
pkg/apiserver/routes/user.go:47:38: expected statement, found ')'
exit status 2
```

Thanks it's all fixed now! 🙇
